apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: test-api
data:
  DB_HOST: postgres-service
  DB_PORT: "5432"
  DB_USER: postgres
  DB_PASSWORD: password123
  DB_NAME: testdb
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector.observabilidade:4317
  OTEL_SERVICE_NAME: test-api
  OTEL_RESOURCE_ATTRIBUTES: service.name=test-api,service.version=1.0.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-api-simple
  namespace: test-api
  labels:
    app: test-api-simple
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-api-simple
  template:
    metadata:
      labels:
        app: test-api-simple
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: test-api
        # Usando uma imagem pública simples para teste
        image: nginx:alpine
        ports:
        - containerPort: 80
        env:
        - name: NGINX_ENTRYPOINT_QUIET_LOGS
          value: "1"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: test-api-simple-service
  namespace: test-api
  labels:
    app: test-api-simple
spec:
  selector:
    app: test-api-simple
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
