apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: test-api
data:
  DB_HOST: postgres-service
  DB_PORT: "5432"
  DB_USER: postgres
  DB_PASSWORD: password123
  DB_NAME: testdb
  OTEL_EXPORTER_OTLP_ENDPOINT: http://signoz-otel-collector.platform:4317
  OTEL_SERVICE_NAME: test-api
  OTEL_RESOURCE_ATTRIBUTES: service.name=test-api,service.version=1.0.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-api
  namespace: test-api
  labels:
    app: test-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-api
  template:
    metadata:
      labels:
        app: test-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: test-api
        image: test-api:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: api-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: test-api-service
  namespace: test-api
  labels:
    app: test-api
spec:
  selector:
    app: test-api
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-api-ingress
  namespace: test-api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: test-api.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: test-api-service
            port:
              number: 8000
