apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-api-local
  namespace: argocd
  labels:
    app.kubernetes.io/name: test-api-local
    app.kubernetes.io/part-of: observability-demo
    environment: local
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # Usando aplicação de exemplo pública do ArgoCD
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: test-api-local
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  revisionHistoryLimit: 3