apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-api-demo
  namespace: argocd
  labels:
    app.kubernetes.io/name: test-api-demo
    app.kubernetes.io/part-of: observability-demo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # Usando repositório público de exemplo do ArgoCD
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: test-api-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  revisionHistoryLimit: 3
