apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-api
  namespace: argocd
  labels:
    app.kubernetes.io/name: test-api
    app.kubernetes.io/part-of: observability-demo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # IMPORTANTE: Ajuste esta URL para seu repositório GitHub
    # Para teste local, você pode usar um repositório público ou configurar autenticação
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: guestbook
    # Alternativa: usar um repositório local ou privado
    # repoURL: https://github.com/SEU-USUARIO/SEU-REPOSITORIO.git
    # path: SRE/test-api/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: test-api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  revisionHistoryLimit: 3
